url: "https://starocrnogorskivremeplov.github.io"
baseurl: ''

# Site settings
title: Starocrnogorski Vremeplov
email: starocrnogorskivremeplov@gmail.com
description: "Službena stranica nevladine udruge 'Starocrnogorski Vremeplov' iz Cetinja."


# Team names, titles and social links
people:
- name: Janko Vujović
  pic: 1
  position: Restaurator, pjesnik, humorista
  social:
    - title: twitter
      url: #
    - title: facebook
      url: http://www.facebook.com/janko.vujovic.12?fref=ts
    - title: stack-overflow
      url: #

- name: Dražen Vujović
  pic: 2
  position: Komercijalist
  social:
    - title: twitter
      url: #
    - title: facebook
      url: http://www.facebook.com/drazen.vujovic.9?fref=ts
    - title: linkedin
      url: #

- name: Nebojša Čelebić
  pic: 3
  position: Fotograf
  social:
    - title: twitter
      url: #
    - title: facebook
      url: https://www.facebook.com/nebojsa.celebic.9?fref=ts
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url: https://www.facebook.com/Starocrnogorski-Vremeplov-236479863399062/
 

# Postal address (add as many lines as necessary)
address:
  - line: Novo naselje br. 2
  - line: Cetinje, Crna Gora

# Build settings
markdown: kramdown
permalink: pretty